version: "3"

services:
  frontend:
    build:
      context: ./front
    ports:
      - "3050:80"
    networks:
      - mynetwork

  backend:
    build:
      context: ./back
    ports:
      - "4001:4001"
    depends_on:
      - db
    command: ./scripts/wait-for-it.sh db:3306 -- npm start
    networks:
      - mynetwork

  db:
    image: mysql:latest
    ports:
      - "3307:3306"
    environment:
      MYSQL_DATABASE: "radiotherapieDB"
      MYSQL_ROOT_PASSWORD: "root"
    networks:
      - mynetwork
    volumes:
      - my-datavolume:/var/lib/mysql
networks:
  mynetwork:
    driver: bridge
volumes:
  my-datavolume:
